### ISSUE TITLE
build过程异常中止

### ISSUE THREAD

**Issue by ohmygods** [meilihao/alfs_docker#1]
我在docker里执行 “$LFSRoot/scripts/run-all.sh ~/build.log ” 这一步骤时，报错中止了，最后的日志显示如下：

+++ done e2fsprogs.sh +++

+++ start stripping-again.sh +++

objcopy: 'ld-2.32.so': No such file

请问这个情况是什么原因，应该怎样解决啊，谢谢。

**Comment by meilihao** [comment]
试试b61a19a47b8e4d771579a0515069e1a158ef2483这个版本, 之前从10.0升到10.1还没时间测试过, 10.0已测试. 这个问题我这周有空会看看.

**Comment by meilihao** [comment]
修复了, 试试
